In PHP, built-in features that accept or read input from a website (via a browser, HTML forms, or API requests) are mostly divided into Superglobal Arrays and I/O Wrapper Streams. [1, 2, 3, 4] 
Here is the complete list of built-in features used to capture website input:
## 1. HTTP Superglobal Arrays
These are built-in, automatically filled arrays that collect data sent from a browser or a client. [1, 5, 6, 7] 

* $_GET: Captures data sent via the URL query string (e.g., ?id=5) after an HTTP GET request.
* $_POST: Captures data sent inside the HTTP request body via an HTML form with method="post".
* $_FILES: Contains items uploaded via an HTTP POST form using enctype="multipart/form-data".
* $_COOKIE: Accesses data sent by the browser through HTTP Cookies.
* $_REQUEST: A combined array containing data from $_GET, $_POST, and $_COOKIE by default.
* $_SERVER: Contains headers, paths, script locations, and request metadata generated by the web server. [8, 9, 10] 

## 2. Raw Input Stream (For JSON, XML, & APIs)
When a website sends data through JavaScript (like fetch or axios) using format payloads like JSON or XML, the standard superglobals will be empty. You must use the built-in read-only input stream. [2, 11] 

* php://input: A built-in stream wrapper that allows you to read raw data from the request body. [2, 12] 

How to use it:

// Reads raw JSON string from a website fetch request
$raw_data = file_get_contents('php://input'); 

// Converts the raw JSON string into a PHP object
$data = json_decode($raw_data); 

## 3. Dedicated Input Functions
PHP provides built-in functions designed specifically to pull and clean website data directly from the server scope:

* filter_input(): Gets a specific external variable by type (like INPUT_GET or INPUT_POST) and optionally filters/sanitizes it simultaneously.
* filter_input_array(): Retrieves multiple external variables at once and filters them.
* getallheaders(): An alias function that grabs all HTTP request headers sent by the website browser. [11, 13, 14, 15, 16] 

Would you like help writing a sample script to handle a specific type of input, like JSON payloads or an HTML form? [10] 


